# Generated by Django 2.0.2 on 2018-02-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_create_category_model_and_add_field_to_idea'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='ideas', to='ideas.Category'),
        ),
    ]
