# Generated by Django 2.0.2 on 2018-02-11 14:15

from django.db import migrations


def migrate_categories(apps, schema_editor):
    Idea = apps.get_model('ideas', 'Idea')
    for idea in Idea.objects.all():
        if idea.category:
            idea.categories.add(idea.category)


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0003_idea_categories'),
    ]

    operations = [
        migrations.RunPython(migrate_categories)
    ]
