# Generated by Django 2.0.2 on 2018-02-11 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0004_migrate_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='category',
        ),
    ]
